sample <- read.table("household_power_consumption.txt",header = TRUE, nrows = 20, sep = ";")
classes <- sapply(sample,class)
data <- read.table("household_power_consumption.txt",header = TRUE, sep=";",colClasses = a,na.strings = "?")
data$Date <- as.Date(x = data$Date,format = "%d/%m/%Y")
data <- subset(data, data$Date >= "2007-02-01" & data$Date <= "2007-02-02")
png("plot1.png",width = 480,height = 480)
hist(set$Global_active_power,ylim=c(0,1200),col="red",main="Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.off()